import { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Button } from "@/components/ui/button";
import { CalendarDays, CheckCircle2, Circle, Trash2 } from "lucide-react";
import { useAppDispatch, useAppSelector } from "@/store/hooks";
import { removeRecipeFromPlan, setShoppingListText, clearPlan } from "@/store/slices/mealPlannerSlice";

export function MealPlannerView() {
  const dispatch = useAppDispatch();
  const plannedRecipes = useAppSelector((state) => state.mealPlanner.plannedRecipes);
  const pantryIngredients = useAppSelector((state) => state.ingredients.items);

  const [copied, setCopied] = useState(false);

  const { missing, have } = useMemo(() => {
    const requiredMap = new Map<string, { quantities: string[] }>();
    
    // Aggregate ingredients across all recipes
    plannedRecipes.forEach(recipe => {
      recipe.requiredIngredients.forEach(ing => {
        const name = ing.name.toLowerCase();
        if (!requiredMap.has(name)) {
          requiredMap.set(name, { quantities: [] });
        }
        if (ing.quantity) {
          requiredMap.get(name)!.quantities.push(ing.quantity);
        }
      });
    });

    const missingItems: { name: string; amounts: string }[] = [];
    const haveItems: { name: string; amounts: string; matchedBy: string }[] = [];

    Array.from(requiredMap.entries()).forEach(([name, data]) => {
      // De-duplicate the string quantities so we dont show "1 cup + 1 cup" if we can help it, or we can just join them. joining them is okay.
      const amounts = data.quantities.length > 0 ? Array.from(new Set(data.quantities)).join(' & ') : 'Some';
      
      const match = pantryIngredients.find(p => name.includes(p.name.toLowerCase()) || p.name.toLowerCase().includes(name));
      if (match) {
        haveItems.push({ name, amounts, matchedBy: match.name });
      } else {
        missingItems.push({ name, amounts });
      }
    });

    return { missing: missingItems, have: haveItems };
  }, [plannedRecipes, pantryIngredients]);

  const handleCopyShoppingList = () => {
    const text = `🛒 Shopping List\n\n` + missing.map(m => `☐ ${m.name} (${m.amounts})`).join('\n') + `\n\nGenerated by PantryPal`;
    navigator.clipboard.writeText(text);
    dispatch(setShoppingListText(text));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleRemove = (id: string) => {
    dispatch(removeRecipeFromPlan(id));
  };

  return (
    <motion.div
      className="flex flex-col h-[calc(100vh-10rem)] space-y-6"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.45 }}
    >
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
        <div>
          <h2 className="page-title">Plan Your Meals</h2>
          <p className="text-muted-foreground">
            Your selected meals and automatically generated shopping list.
          </p>
        </div>
        {plannedRecipes.length > 0 && (
          <div className="flex items-center gap-2">
            <Button variant="outline" onClick={() => dispatch(clearPlan())} className="rounded-full">
              Reset Plan
            </Button>
            <Button onClick={handleCopyShoppingList} className="bg-primary hover:bg-primary rounded-full border-0 text-[#10120f]">
              {copied ? "Copied!" : "Copy Shopping List"}
            </Button>
          </div>
        )}
      </div>

      <div className="flex-1 min-h-0">
        <ScrollArea className="h-full pr-4">
          <div className="grid lg:grid-cols-12 gap-8 pb-20">
            {/* Left Column: Planned Recipes */}
            <div className="lg:col-span-7 flex flex-col space-y-4">
              <h3 className="text-xl font-bold mb-2">Planned Meals ({plannedRecipes.length})</h3>
              <div className="min-h-[200px] rounded-2xl border border-[#e8eaec] bg-white p-4">
                {plannedRecipes.length === 0 ? (
                  <div className="m-2 flex h-48 flex-col items-center justify-center rounded-xl border border-border/60 bg-muted/20 text-muted-foreground">
                    <CalendarDays className="h-12 w-12 mb-4 opacity-20" />
                    <p className="font-semibold text-lg text-foreground">No meals planned yet.</p>
                    <p className="text-sm mt-1 max-w-sm text-center">Browse your recipes and click "Add to Plan" to start generating your shopping list.</p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    {plannedRecipes.map(recipe => (
                      <Card key={recipe.id} className="flex flex-col overflow-hidden rounded-[24px] border-[#e8eaec] bg-white py-0 sm:flex-row">
                        {recipe.image ? (
                          <div className="h-40 shrink-0 overflow-hidden bg-[#f6f7f8] sm:h-auto sm:w-44">
                            <img src={recipe.image} alt={recipe.title} className="w-full h-full object-cover" />
                          </div>
                        ) : (
                          <div className="flex h-40 shrink-0 items-center justify-center bg-[#f6f7f8] sm:h-auto sm:w-44">
                            <CalendarDays className="h-10 w-10 text-primary/30" />
                          </div>
                        )}
                        <div className="flex-1 p-5 flex flex-col justify-between">
                          <div>
                            <div className="flex justify-between items-start gap-2">
                              <h4 className="font-bold text-lg leading-tight line-clamp-2">{recipe.title}</h4>
                              <Button variant="ghost" size="icon" className="shrink-0 -mt-2 -mr-2 text-muted-foreground hover:bg-destructive/10 hover:text-destructive" onClick={() => handleRemove(recipe.id)}>
                                <Trash2 className="h-5 w-5" />
                              </Button>
                            </div>
                            {recipe.sourceType === 'ai' && (
                              <Badge variant="secondary" className="mt-3 bg-primary/10 text-primary border-transparent">
                                AI Generated
                              </Badge>
                            )}
                          </div>
                          <p className="text-sm text-muted-foreground mt-4 font-medium">
                            {recipe.requiredIngredients.length} Ingredients Checked
                          </p>
                        </div>
                      </Card>
                    ))}
                  </div>
                )}
              </div>
            </div>

            {/* Right Column: Ingredients Summary */}
            <div className="lg:col-span-5 flex flex-col space-y-4">
              <h3 className="text-xl font-bold mb-2">Shopping List</h3>
              <div className="min-h-[200px] rounded-2xl border border-[#e8eaec] bg-white p-4">
            {plannedRecipes.length === 0 ? (
              <div className="flex h-full min-h-[300px] items-center justify-center rounded-xl border border-border/60 bg-muted/20 text-muted-foreground opacity-50">
                Plan a meal to see your list.
              </div>
            ) : (
              <div className="space-y-8">
                {/* Missing */}
                <div>
                  <h4 className="font-bold flex items-center gap-2 mb-4 text-orange-600 border-b border-orange-100 pb-2">
                    <Circle className="h-4 w-4" /> To Buy ({missing.length})
                  </h4>
                  {missing.length === 0 ? (
                    <p className="rounded-xl border border-[#e8eaec] bg-white p-4 text-center text-sm text-muted-foreground">You have everything you need!</p>
                  ) : (
                    <ul className="space-y-3">
                      {missing.map((item, idx) => (
                        <li key={idx} className="flex flex-col gap-1 rounded-xl border border-[#10120f] bg-[#10120f] p-3 text-sm">
                          <span className="font-bold capitalize text-white">{item.name}</span>
                          <span className="text-xs font-medium text-[rgba(255,255,255,0.62)]">{item.amounts}</span>
                        </li>
                      ))}
                    </ul>
                  )}
                </div>

                {/* Have */}
                <div>
                  <h4 className="font-bold flex items-center gap-2 mb-4 text-green-700 border-b border-green-100 pb-2">
                    <CheckCircle2 className="h-4 w-4" /> You Have ({have.length})
                  </h4>
                  {have.length === 0 ? (
                    <p className="text-sm text-muted-foreground">Nothing matching from pantry.</p>
                  ) : (
                    <ul className="space-y-3">
                      {have.map((item, idx) => (
                        <li key={idx} className="flex flex-col gap-1 rounded-xl border border-[#10120f] bg-[#10120f] p-3 text-sm opacity-100">
                          <div className="flex justify-between items-start gap-2">
                            <span className="font-bold capitalize text-white line-through">{item.name}</span>
                            <span className="text-[10px] font-bold text-green-800 bg-green-200/70 px-2 py-0.5 rounded-sm">In Pantry</span>
                          </div>
                          <span className="text-xs font-medium text-[rgba(255,255,255,0.62)]">{item.amounts}</span>
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              </div>
            )}
            </div>
          </div>
        </div>
        </ScrollArea>
      </div>
    </motion.div>
  );
}
